// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCue1--rKjhdbzM3YY-q92PQQO1KTvx_lI',
    appId: '1:788138999982:web:ef9b301d52cec3da7b2d3f',
    messagingSenderId: '788138999982',
    projectId: 'cloudgaming-e7494',
    authDomain: 'cloudgaming-e7494.firebaseapp.com',
    storageBucket: 'cloudgaming-e7494.appspot.com',
    measurementId: 'G-W2TC3724V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGAJVzuR_joDZu54o7zfktAUZGnEopfak',
    appId: '1:788138999982:android:a441b16384eeebfd7b2d3f',
    messagingSenderId: '788138999982',
    projectId: 'cloudgaming-e7494',
    storageBucket: 'cloudgaming-e7494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-rJK6lbOvEXpXeKgLeY-6Ic3r0e977Ao',
    appId: '1:788138999982:ios:dd288374f1745ac67b2d3f',
    messagingSenderId: '788138999982',
    projectId: 'cloudgaming-e7494',
    storageBucket: 'cloudgaming-e7494.appspot.com',
    iosBundleId: 'com.example.cloudGaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-rJK6lbOvEXpXeKgLeY-6Ic3r0e977Ao',
    appId: '1:788138999982:ios:8bde2f935acccefd7b2d3f',
    messagingSenderId: '788138999982',
    projectId: 'cloudgaming-e7494',
    storageBucket: 'cloudgaming-e7494.appspot.com',
    iosBundleId: 'com.example.cloudGaming.RunnerTests',
  );
}
